FORMAT: 1A
HOST: http://collegedb.me/api

# College DB

College DB is an API for easily retrieving information about Universities, Degrees, and States in the United States.

## Universities Collection [/universities]

### List All Universities [GET]

+ Response 200 (application/json)

        [
            {
                "id": 0,
                "name": "The University of Texas at Austin",
                "is_public": true,
                "num_students": 50000,
                "website_URL": "http://utexas.edu",
                "academic_cost": 5000
            },
            {
                "id": 1,
                "name": "St. Edward's",
                "is_public": false,
                "num_students": 10000,
                "website_URL": "http://stedwards.edu",
                "academic_cost": 15000
            }
        ]


## A Single University [/universities/{id}]

### List a university with the given {id} [GET]
Gives back information for a single university plus its state and degrees.

+ Response 200 (application/json)

        {
            "id": 0,
            "name": "The University of Texas at Austin",
            "is_public": true,
            "num_students": 50000,
            "website_URL": "http://utexas.edu",
            "academic_cost": 5000,
            "state_id":0, 
            "state_name": "Texas",
            "degrees": [
                {"degree_id":0, "degree_name":"Education"},
                {"degree_id":1, "degree_name":"Engineering"}
            ]
        }
        
## States Collection [/states]

### List All States [GET]

+ Response 200 (application/json)

        [
            {
                "id": 0,
                "name": "Texas",
                "region": "South",
                "average_public_tuition": 5000,
                "average_private_tuition": 15000,
                "number_colleges": 500
            },
            {
                "id": 1,
                "name": "California",
                "region": "West",
                "average_public_tuition": 10000,
                "average_private_tuition": 30000,
                "number_colleges": 300
            }
        ]


## A Single State [/states/{id}]

### List a state with the given {id} [GET]
Gives back information for a single state plus a list of its universities.

+ Response 200 (application/json)

        {
                "id": 0,
                "name": "Texas",
                "region": "South",
                "average_public_tuition": 5000,
                "average_private_tuition": 15000,
                "number_colleges": 500,
                "universities": [ 
                {"university_id":0, "university_name":"The University of Texas at Austin"},
                {"university_id":0, "university_name":"St. Edward's"}
                ]
            }
        


## Degrees Collection [/degrees]

### List All Degrees [GET]

+ Response 200 (application/json)

        [
            {
                "id": 0,
                "name": "Engineering",
                "num_public_offer": 5,
                "num_private_offer": 50,
                "num_percent_public": 6.75,
                "num_percent_private": 7.98
            },
            {
                "id": 1,
                "name": "Engineering",
                "num_public_offer": 10,
                "num_private_offer": 5,
                "num_percent_public": 5.00,
                "num_percent_private": 8.33
            }
        ]


## A Single Degree [/degrees/{id}]

### List a degree with the given {id} [GET]
Gives back information for a single degree plus a list of universities that offer that degree.

+ Response 200 (application/json)

        {
                "id": 0,
                "name": "Engineering",
                "num_public_offer": 5,
                "num_private_offer": 50,
                "num_percent_public": 6.75,
                "num_percent_private": 7.98,
                "universities": [ 
                {"university_id":0, "university_name":"The University of Texas at Austin"},
                {"university_id":0, "university_name":"St. Edward's"}
                ]
            }
            
## Search [/search]

### Search based on given query parameters [GET]
Give ordered search results based on given query parameters.

+ Response 200 (application/json)

        [
            {"name": "Texas", "type": "states", "id": 1, "matching_words": ["Texas"], "match_type": "and"},
            {"name": "Texas State University", "type": "universities", "id": 34, "matching_words": ["Texas"], "match_type": "and"}
        ]